services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: lm_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Password123"
    ports:
      - "1433:1433"
    volumes:
      - lm_sql_data:/var/opt/mssql

  api:
    build:
      context: ./server
    container_name: lm_api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=TestReactDb;User=sa;Password=YourStrong@Password123;TrustServerCertificate=True"
    ports:
      - "5000:8080"
    depends_on:
      - db

volumes:
  lm_sql_data:
